lolautruche_payline_notification:
    path:     /payline/notification
    defaults: { _controller: LolautruchePaylineBundle:Payline:paymentNotification }

lolautruche_payline_back_to_shop:
    path:     /payline/back-to-shop
    defaults: { _controller: LolautruchePaylineBundle:Payline:backToShop }
